<section class="homeAdminUser">
    <h3>Ajout d'un genre</h2>
    <form action="admin/addcategories" method="POST">
        <label for="newGenre">Ajouter</label>
        <input type="text" name="newGenre">
        <button class="btnForm" type="submit">Valider</button>
    </form>

    <h3>Ajout d'un type</h3>
    <form action="admin/addcategories" method="POST">
        <label for="newType">Ajouter</label>
        <input type="text" name="newType">
        <button class="btnForm" type="submit">Valider</button>
    </form>
</section>
<div id="scroll_to_top">
    <a href="admin/useradmin#top" title="Retour haut"><img src="assets/img/icons/top.png" alt="Retourner en haut" /></a>
 </div> 
</section>
</main>