<?php
require('../views/inc/head.phtml');
require('../views/inc/header.phtml');

?>
<main class="adminContainer">


    <!-- notifications   -->
    <?php
    require '../views/inc/notifications.phtml';
    ?>

    <!--Formulaire d'inscription'-->
    <h1>Page d'Administration</h1>
    <div class="adminPanel">
        <nav class="sidenav">
            <a href="admin/useradmin.php">Utilisateurs</a>
            <a href="admin/poiadmin.php">P.O.I.</a>
            <a href="admin/demandesadmin.php">Demandes</a>
        </nav>
        <div class="homeAdmin">
            <p>Bienvenue dans votre espace administration</p>
            <p>Dans cet espace vous pouvez gérer le CRUD (Create, Read, Update, Delete) pour :</p>
            <ul>
                <li>Les utilisateurs</li>
                <li>Les points d'intérêt (P.O.I.)</li>
            </ul>
            <p>Vous pouvez également consulter les demandes des utilisateurs</p>
            <p>Pour faire les modifications ou accéder aux demandes, il vous suffit de cliquer sur le lien correspondant à gauche</p>
        </div>
    </div>
</main>
<?php
require('../views/inc/footer.phtml');
?>

</body>

</html>