
        <div class="homeAdmin">
            <p>Bienvenue dans votre espace administration</p>
            <p>Dans cet espace vous pouvez gérer le CRUD (Create, Read, Update, Delete) pour :</p>
            <ul>
                <li>Les utilisateurs</li>
                <li>Les points d'intérêt (P.O.I.)</li>
            </ul>
            <p>Vous pouvez également consulter les demandes des utilisateurs</p>
            <p>Pour faire les modifications ou accéder aux demandes, il vous suffit de cliquer sur le lien correspondant à gauche</p>
        </div>
    </div>
</main>
