<?php
require('../Views/inc/head.phtml');
require('../Views/inc/header.phtml');

?>
<main class="adminContainer">


    <!-- notifications   -->
    <?php
    require '../Views/inc/notifications.phtml';
    ?>

    <!--Formulaire d'inscription'-->
    <h1>Page d'Administration</h1>
    <div class="adminPanel">
        <nav class="sidenav">
            <a href="#">Utilisateurs</a>
            <a href="#">P.O.I.</a>
            <a href="#">Tags</a>
        </nav>
        <div class="homeAdmin">
            <p>Bienvenue dans votre espace administration</p>
            <p>Dans cet espace vous pouvez gérer le CRUD (Create, Read, Update, Delete) pour :</p>
            <ul>
                <li>Les utilisateurs</li>
                <li>Les points d'intérêt (P.O.I.)</li>
                <li>Les tags utilisés</li>
            </ul>
            <p>Pour faire les modifications il vous suffit de cliquer sur le lien correspondant à gauche</p>
        </div>
    </div>
</main>
<?php
require('../Views/inc/footer.phtml');
?>

</body>

</html>