<section class="editpoi">
    <h2> Edition d'un lieu</h2>
            <a href="admin/poiadmin" class="btnForm">Retour</a>
            
        <form action="admin/modifypoi?id=<?= intval($_GET['id']) ?>" method="post" enctype="multipart/form-data">
            <fieldset>  

                <!-- Le lieu s'affiche avec les information de la BDD en value -->
                <legend>Modifiez les informations nécessaires</legend>
                <div class="form-group">
                    <label for="name">Nom : </label>       
                    <input class=" inputpoi" type="text" name="name" value="<?=htmlspecialchars($shop['name'])?>" required>
                </div>
                <div class="form-group">
                    <label for="lat">Latitude : </label>       
                    <input class=" inputpoi" type="text" name="latitude" value="<?=floatval($shop['lat'])?>" required>
                </div>
                <div class="form-group">
                    <label for="longitude">Longitude : </label>       
                    <input class=" inputpoi" type="text" name="longitude" value="<?=floatval($shop['longitude'])?>" required>
                </div>
                <div class="form-group">
                    <label for="genre">Genre : </label>
                    <select name="genre" id="genre">

                        <!-- On boucle sur le genre et le genre pour tous les avoir -->
                        <?php foreach($genres as $genre):?>
                        <option <?php if ($genre['id'] === $shop['genreId']):?>
                        <?=  " selected "?>
                        <?php endif;?>                        
                        value="<?=intval($genre['id'])?>"><?=htmlspecialchars($genre['genre'])?></option>
                        <?php endforeach?>
                    </select>                    
                </div>
                <div class="form-group">
                    <label for="type">Type : </label>
                    <select name="type" id="">

                        <!-- Idem pour le type -->
                        <?php foreach($types as $type):?>
                        <option <?php if ($type['id'] === $shop['typeId']):?>
                        <?=  " selected "?>
                        <?php endif;?>                     
                        value="<?=intval($type['id'])?>"><?=htmlspecialchars($type['type'])?></option>
                        <?php endforeach?>
                    </select>                    
                </div>

                <div class="form-group">
                    <label for="adresse">Adresse : </label>       
                    <input class=" inputpoi" type="text" name="adresse" value="<?=htmlspecialchars($shop['adresse'])?>" required>
                </div>
                <div class="form-group">
                    <label for="cp">Cp : </label>
                    <input type="text" class="inputpoi" name="cp" value="<?=intval($shop['cp'])?>" required>                   
                </div>
                <div class="form-group">
                    <label for="cp">Ville : </label>
                    <input type="text" class="inputpoi" name="commune" value="<?=htmlspecialchars($shop['commune'])?>" required>                   
                </div>
                <div class="form-group">
                    <label for="opening">Horaires : </label>
                    <input type="text" class="inputpoi" name="opening" value="<?=htmlspecialchars($shop['opening'])?>" >                   
                </div>
                <div class="form-group">
                    <label for="phone">Téléphone : </label>
                    <input type="text" class="inputpoi" name="phone" value="<?=htmlspecialchars($shop['phone'])?>" >                   
                </div>
                <div class="form-group">
                    <label for="website">Site Web : </label>
                    <input type="text" class="inputpoi" name="website" value="<?=htmlspecialchars($shop['website'])?>" >                   
                </div>
                <div class="form-group">
                    <label for="image">Photo : </label>
                    <input type="file" class="inputpoi" name="picture" accept="image/png, image/jpeg">                   
                </div>                   
            </fieldset> 
                </br>
                <button class="btnForm" type="submit">Modifier</button>
                <button class="btnFormDelete" type="submit" name="delete"  onclick="return confirm('Êtes vous sur de vouloir supprimer?')" value="delete">Supprimer</button>
        </form>
</section>
</main>