<section class="editcategories">
    <a href="admin/categoriesadmin" class="btnForm">Retour</a>
    <h2> Edition/suppression du type</h2>
    <p><span><i class="fas fa-exclamation-triangle"></i></span > Le bouton supprimer n'apparaitra que si AUCUN lieu n'a ce type de défini <span><i class="fas fa-exclamation-triangle"></i></span></p>   
        <form action="admin/edittype?id=<?= intval($_GET['id']) ?>" method="post">
            <fieldset>Genre à modifier</fieldset> 
                <input type="text" name="editedType" value="<?=htmlspecialchars($type['type'])?>">
                <button class="btnForm" type="submit">Modifier</button>
                <?php if(count($poitype) === 0):?>
                <button class="btnFormDelete" type="submit" name="deleteType" value="delete">Supprimer</button>
                <?php endif?>          
        </form> 
            <?php if(count($poitype) > 0):?>
            <p>Il reste <?=count($poitype)?> lieu(x) avec ce type</p>
            <?php endif;?>
</section>
</section>
</main>