<section class="editcategories">
    <a href="admin/categoriesadmin" class="btnForm">Retour</a>
    <h2> Edition/suppression du genre</h2>
    <p><span><i class="fas fa-exclamation-triangle"></i></span > Le bouton supprimer n'apparaitra que si AUCUN lieu n'a ce genre de défini <span><i class="fas fa-exclamation-triangle"></i></span></p>    
        <form action="admin/editgenre?id=<?= intval($_GET['id']) ?>" method="post">
            <fieldset>Genre à modifier</fieldset> 
                <input type="text" name="editedGenre" value="<?=htmlspecialchars($genre['genre'])?>">
                <button class="btnForm" type="submit">Modifier</button>
                <?php if(count($poigenre) === 0):?>
                <button class="btnFormDelete" type="submit" name="deleteGenre" value="delete">Supprimer</button>          
                <?php endif?>  
        </form>
        <?php if(count($poigenre) > 0):?>
            <p>Il reste <?=count($poigenre)?> lieu(x) avec ce genre</p>
            <?php endif;?>
            <?php if(count($poigenre) === 0):?>
            <p>Aucun lieu n'a ce genre, vous pouvez supprimer le libellé en toute sécurité !</p>
            <?php endif;?>

</section>
</section>
</main>