<section class="editcategories">
    <a href="admin/categoriesadmin" class="btnForm">Retour</a>
    <h2> Edition/suppression du genre</h2>
    <p><span><i class="fas fa-exclamation-triangle"></i></span > Le bouton supprimer n'apparaitra que si AUCUN lieu n'a ce genre de défini <span><i class="fas fa-exclamation-triangle"></i></span></p>    
        
    <!-- Formulaire d'édition du genre -->
    <form action="admin/editgenre?id=<?= intval($_GET['id']) ?>" method="post">
            <fieldset>Genre à modifier</fieldset> 
                <input type="text" name="editedGenre" value="<?=htmlspecialchars($genre['genre'])?>">
                <button class="btnForm" type="submit">Modifier</button>

                <!-- Le bouton supprimer n'apparait que si le genre n'est pas actuellement utilisé -->
                <?php if(count($poigenre) === 0):?>
                <button class="btnFormDelete" onclick="return confirm('Êtes vous sur de vouloir supprimer?')" type="submit" name="deleteGenre" value="delete">Supprimer</button>          
                <?php endif?>  
        </form>

        <!-- On vérifie si des lieux ont actuellement ce genre -->
        <?php if(count($poigenre) > 0):?>
            <p>Il reste <?=count($poigenre)?> lieu(x) avec ce genre</p>
            <a href="admin/poiadmin">Le(s) trouver</a>
            <?php endif;?>

            <!-- Aucun lieu avec genre actuellement -->
            <?php if(count($poigenre) === 0):?>
            <p>Aucun lieu n'a ce genre, vous pouvez supprimer le libellé en toute sécurité !</p>
            <?php endif;?>

</section>
</section>
</main>