<section class="homeAdminUser">
    <h2>Points d'intérêt</h2>
    <p>Ici vous pouvez voir tous les lieux dans la base, les créer, les supprimer, les éditer...</p>
    <p>La recherche peut être faite par nom, genre ou type.</p>
    <form action="admin/poiadmin" method="post">
        <input type="text" name="name" placeholder="Nom ou genre ou type">
        <button type="submit" class="btnForm">OK/RAZ</button>
        <?php
        if ($count == 0) {
            echo "<p>Il n'y a pas de résultat à votre recherche</p>";
        }
        ?>
    </form>
    <a href="admin/addpoi" class="btnFormAdd">+</i></a>
    <table>
        <thead>
            <tr>
                <th>Nom</th>
                <th>Genre</th>
                <th>Type</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($poi as $item) : ?>
                <tr>
                    <td><?= htmlspecialchars($item['name']) ?></td>
                    <td><?= htmlspecialchars($item['genre']) ?></td>
                    <td><?= htmlspecialchars($item['type']) ?></td>
                    <td><a href="admin/editpoi?id=<?= $item['shopId'] ?>" class="btnForm">Modifier</a></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    </div>
</section>
<div id="scroll_to_top">
    <a href="admin/poiadmin#top" title="Retour haut"><img src="assets/img/icons/top.png" alt="Retourner en haut" /></a>
</div>
</section>
</main>