<section class="homeAdminUser">
    <h2>Utilisateurs</h2>
    <p>Ici vous pouvez voir tous les POI dans la base, les créer, les effacer, les éditer...</p>
    <form action="admin/poiadmin" method="post">
            <input type="text" name="name" placeholder="Nom lieu">
            <button type="submit" class="btnForm">OK/RAZ</button>
            <?php 
            if ($count == 0){
                echo "<p>Il n'y a pas de résultat à votre recherche</p>";
            }
            ?>
    </form>
    <table>
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Type</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($poi as $item) : ?>
                <tr>
                    <td><?= intval($item['id']) ?></td>
                    <td><?= htmlspecialchars($item['name']) ?></td>
                    <td><?= htmlspecialchars($item['type']) ?></td>
                    <td><a href="admin/editpoi?id=<?=$item['id'] ?>" class="btnForm">Modifier</a></td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    </div>
</section>
<div id="scroll_to_top">
    <a href="admin/poiadmin#top" title="Retour haut"><img src="assets/img/icons/top.png" alt="Retourner en haut" /></a>
 </div> 
</section>
</main>