<footer class="footer">
        <div class="container cols cols--2 gutter">

            <section class="social">
                <h2>Sur les réseaux sociaux</h2>
                <div>
                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </section>
            <nav>
                <h2>A propos</h2>
                <ul class="unstyled">
                    <li><a href="#">Qui sommes-nous ?</a></li>
                    <li><a href="#">Nos services</a></li>
                    <li><a href="#">Contactez-nous</a></li>
                </ul>
            </nav>
            <nav>
                <h2>A propos</h2>
                <ul class="unstyled">
                    <li><a href="#">Plan du site</a></li>
                    <li><a href="#">Foire Aux Questions</a></li>

                    <li><a href="#">Informations légales</a></li>
                </ul>
            </nav>
        </div>
    </footer>
       <!-- Chargement JS PRINCIPAL -->
       <script src="js/main.js"></script>