<footer class="footer">
        <div class="footercontainer">

            <section class="social">
                <h2>Réseaux sociaux</h2>
                <div>
                    <a href="https://www.facebook.com/gibaud.chris/"><i class="fab fa-facebook-f"></i></a>
                    <a href="https://www.instagram.com/darky13540/?hl=fr"><i class="fab fa-instagram"></i></a>
                    <a href="https://github.com/Darky13540/"><i class="fab fa-github"></i></a>
                    <a href="https://www.linkedin.com/in/christophe-gibaud-20243488/"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </section>
            <nav>
                <h2>A propos</h2>
                <ul class="unstyled">
                    <li><a href="#">Qui sommes-nous ?</a></li>
                    <li><a href="#">Nos services</a></li>
                    <li><a href="contact.php">Contactez-nous</a></li>
                </ul>
            </nav>
        </div>
        <div class="greetings">
            <p>GIBAUD Christophe 2021 ©</p>
        </div>
    </footer>
       <!-- Chargement JS PRINCIPAL -->
       <script src="js/main.js"></script>