<body>
    <header class="header">
        <img src="img/logo.png" alt="logo">
        <nav>
            <ul>
                <li><a href="index.php" title="Accueil">Accueil</a></li>
                <li><a href="easymap.php" title="carte des lieux">Map</a></li>
                <li><a href="menus.html">Menus</a></li>
                <li><a href="contacts.html">Contact</a></li>
            </ul>
        </nav>
    </header>