<body>

    <header class="header">
        
        <a href="index.php" id="logo"><img src="img/logo2.png" alt="logo"></a>
        <div id="hamburger">
            <div id="hamburger-content">
                <nav>
                    <ul>
                        <li><a href="index.php" title="Accueil">Accueil</a></li>
                        <li><a href="easymap.php" title="carte des lieux">Map</a></li>
                        <li><a href="contacts.html">Contact</a></li>
                <?php if(!isset($_SESSION["user"])):?>                    
                        <li><a href="inscription.php">Inscription</a></li>
                        <li><a href="connexion.php">Connexion</a></li>
                <?php else:?>        
                    <li><a href="profil.php">Bienvenue <?= htmlspecialchars($_SESSION["user"]["pseudo"]) ?></a></li>
                    <li><a href="deconnexion.php">Déconnexion</a></li>
                <?php endif;?>
                <?php if (isset($_SESSION["user"]["role"])):
                      if ($_SESSION["user"]["role"] == 1):?>
                    <li><a href="admin/administration.php">Administration</a></li>
                <?php endif;?>   
                <?php endif;?>      
                    </ul>
                </nav>
            </div>
            <button id="hamburger-button">&#8801</button>
            <div id="hamburger-sidebar">
                <button id="close-burger">&#10540</button>
                <div id="hamburger-header"><img src="img/logo2.png" alt="logo"></div>
                <div id="hamburger-sidebar-body"> </div>
            </div>
        </div>

    </header>

    