<body>
    <header class="header">
        
        <a href="index.php" id="logo"><img src="img/logo.png" alt="logo"></a>
        <div id="hamburger">
            <div id="hamburger-content">
                <nav>
                    <ul>
                        <li><a href="index.php" title="Accueil">Accueil</a></li>
                        <li><a href="easymap.php" title="carte des lieux">Map</a></li>
                        <li><a href="menus.html">Menus</a></li>
                        <li><a href="contacts.html">Contact</a></li>
                        <li><a href="contacts.html">Inscription/Connexion</a></li>
                    </ul>
                </nav>
            </div>
            <button id="hamburger-button">&#8801</button>
            <div id="hamburger-sidebar">
                <button id="close-burger">&#10540</button>
                <div id="hamburger-header"><img src="img/logo.png" alt="logo"></div>
                <div id="hamburger-sidebar-body"> </div>
            </div>
        </div>

    </header>






    <!-- SAVE
     <body>
    <header class="header">
        <img src="img/logo.png" alt="logo">
        <nav>
            <ul>
                <li><a href="index.php" title="Accueil">Accueil</a></li>
                <li><a href="easymap.php" title="carte des lieux">Map</a></li>
                <li><a href="menus.html">Menus</a></li>
                <li><a href="contacts.html">Contact</a></li>
            </ul>
        </nav>
    </header> -->