<?php if (hasFlashes('error')) : ?>
    <div class="notification">
        <div class="iconError">
            <img src="assets/img/wheelchairerror.svg" alt="notification icon">
        </div>
        <div class="textError">
            <?php foreach (getFlashes('error') as $message) : ?>
                <p><?= $message ?></p>
            <?php endforeach ?>
        </div>
    <?php endif ?>
    <?php if (hasFlashes('success')) : ?>
        <div class="iconSuccess">
            <img src="assets/img/success.svg" alt="notification icon" />
        </div>
        <div class="textSuccess">
            <?php foreach (getFlashes('success') as $message) : ?>
                <p><?= $message ?></p>
    <?php endforeach ?>
        </div>
    </div>
    <?php endif ?>