<main class="maincontainer">
    <h1>Bienvenue sur Easy-PMR</h1>
    <section class="ipsum">

        <h2>Bonjour à tous et toutes !</h2>
            <h3>Quel est le but d'Easy-PMR?</h3>
                <p>Le but de ce site est de faciliter la vie des personnes à mobilité réduite (dites <a href="https://fr.wikipedia.org/wiki/Accessibilité_aux_personnes_handicapées" target="_blank" title="wiki PMR">PMR</a>). Pour ces personnes il n'est pas rare de se déplacer dans un lieu (administration, magasin, infrastructures diverses...) et ne pas pouvoir y accéder faute d'aménagement ou de stationnement adapté!!!</p>
                <figure>
                            <div class="image">
                            <img src="assets/img/Obstacle-PMR1.jpg" alt="obstacle">
                            <figcaption>"Qui ne s'est pas déjà retrouvé devant cette situation?"</figcaption>
                        </div>
                        </figure>
                <p>Car même si la <a href="https://www.legifrance.gouv.fr/loda/id/JORFTEXT000000809647/" target="_blank" title="loi PMR">loi d'accessibilité du 11 février 2005</a> impose aux constructeurs de prévoir cette accessibilité dans les locaux neufs, beaucoup d'anciens bâtiments ne sont pas encore aux normes</p>

            <h3>Pourquoi avoir créer Easy-PMR</h3>
                <p>Étant moi même <a href="https://fr.wikipedia.org/wiki/Aidant_familial" title="Def aidant" target="_blank">aidant</a> de mon épouse atteinte de <a href="https://fr.wikipedia.org/wiki/Sclérose_en_plaques" title="Def SEP" target="_blank">Sclérose en Plaques</a>, j'ai été confronté à des situations parfois rocambolesques, j'ai trouvé assez peu d'informations quant à l'accessibilité des différents établissements publics ou privés qui aurait permis de préparer la visite ou d'aller dans un autre lieu plus adapté.</p>
                <p>Afin d'éviter de rester bloqué et de rajouter des contraintes là où il y en a déjà suffisamment, ce site espère pouvoir vous aider au quotidien, que vous soyez le moins possible pris au dépourvu et ainsi pouvoir réinvestir l'espace public.</p>
                <p>Parce que nous sommes tous égaux mais tous différents nous essayons ici de répondre au maximum de problématiques mais ne pouvant le faire de manière exhaustive ce site se veut participatif pour que chacun puisse y rajouter ses observations. Alors d'avance merci et faisons en sorte qu'ensemble le sigle PMR deviennent <span>P</span>ersonne à <span>M</span>obilité <span>R</span>éelle !!</p>

                <p id="center"><span>L'accessibilité c'est pour tous et toutes ! Rejoignez la communauté des Roulettes Girls et Roulettes Boys</span></p>
                <a href="inscription"><button class="btnForm">Devenez un(e) Roulettes Girl/Boy Helper</button></a>
    </section>
</main>