
<main class="mainDetails">
    <h1>Détails du lieu</h1>
    <div class="identite">
        <section class="identite">
            <h1><?= htmlspecialchars($details['name']); ?></h1>

            <button class="btnForm"><a href="easymap">Retour à la carte</a></button>
        </section>
    </div>
    <div class="tag">
        <section class="tagPark">
            <h2>Informations concernant l'accès depuis un parking</h2>
        </section>
        <section class="tagExt">
            <h2>Informations concernant l'accès depuis l'extérieur</h2>
        </section>
        <section class="tagInt">
            <h2>Informations concernant l'intérieur</h2>
        </section>
        <section class="commodites">
            <h2>Informations concernant les commodités</h2>
        </section>
    </div>
</main>