<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Détail POI</title>
</head>
<?php 
require ('inc/head.phtml');
require ('inc/header.phtml'); ?>
<body>
    <div class="poiDetails">
        <h1><?= $details['name'];?></h1>

    </div>
    <a href="easymap.php">Retour à la carte</a>
</body>
</html>
<?php 
require ('inc/footer.phtml'); ?>