<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Détail POI</title>
</head>
<body>
    <div class="test">
        <h1>TITRE</h1>
        <p>Le magasin s'appelle :<?= $details['name'];?></p>
    </div>
    <a href="easymap.php">Retour à la carte</a>
</body>
</html>