    <main class="maineasymap">

        <!-- recherche -->
        <section class="filtres">
            <form action="easymap" method="post">
                <div class="form-group">
                    <label for="query"><i class="fas fa-search-location"></i></label>
                    <input type="text" name="query" placeholder="Recherche par nom, type, genre..">
                </div>
                <button type="submit" class="btnForm">OK/RAZ</button>
            </form>

            <!-- On affiche le résultat de la recherche -->
            <?php
            if ($count > 0) {
                echo "<p>Il y a " . $count . " résultat(s) à votre recherche</p>";
            } else {
                echo "<p>Il n'y a aucun résultat à votre recherche : " . htmlspecialchars($_POST['query']) . " !</p>";
            }
            ?>
        </section>


        <div class="mapListContainer">
            <!-- container de la carte -->
            <div id="mapid"></div>

            <!-- Résultats -->
            <div class="listpoi">
                <!-- On boucle sur chaque retour de BDD, tous ou en recherche -->
                <?php foreach ($poi as $item) : ?>
                    <div class="item js-marker"
                            data-id="<?= intval($item['shopId']) ?>" 
                            data-type="<?= htmlspecialchars($item['type']) ?>" 
                            data-name="<?= htmlspecialchars($item['name']) ?>" 
                            data-lat="<?= floatval($item['lat']) ?>" 
                            data-long="<?= floatval($item['longitude']) ?>">
                            <a href="details?id=<?= intval($item['shopId']) ?>" title="page de détails">

                            <!-- si l'image est présente en BDD on l'appelle, sinon fake -->
                            <?php if($item['image'] !== ""):?>
                            <img src="upload/<?=htmlspecialchars($item['image'])?>" alt="photo poi">
                            <?php else:?>
                            <img src="https://fakeimg.pl/200/" alt="photo poi">
                            <?php endif;?>

                            <p><span><?= htmlspecialchars($item['name']) ?></span></p>
                            <p><?= htmlspecialchars($item['genre']) ?></p>
                            <p><?= htmlspecialchars($item['type']) ?></p>
                        </a>
                    </div>
                <?php endforeach; ?>
            </div>
            <!-- Ancre pour remonter au top du site -->
            <div id="scroll_to_top" class="scroll_to_top">
                <a href="easymap#top"><img src="assets/img/icons/top.png" alt="Retourner en haut" /></a>
            </div>
    </main>

    <!-- Chargement librairie JS Leaflet pour affichage de la carte -->
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js" integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA==" crossorigin=""></script>

    <!-- Chargement JS MAP -->
    <script src="assets/js/easymap.js"></script>