<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Leaflet CSS -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css"
   integrity="sha512-xodZBNTC5n17Xt2atTPuE1HxjVMSvLVW9ocqUKLsCC5CXdbqCmblAshOMAS6/keqq/sMZMZ19scR4PsZChSR7A=="
   crossorigin=""/>
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"
        integrity="sha512-HK5fgLBL+xu6dm/Ii3z4xhlSUyZgTT9tuc/hSrtw6uzJOvgRr2a9jyxxT1ely+B+xFAmJKVSTbpM/CuL7qxO8w=="
        crossorigin="anonymous" />
    <link rel="stylesheet" href="css/normalize.css">
    <link rel="stylesheet" href="css/style.css">
    <title>Easy-PMR</title>
</head>

<body>
    <header class="header">
        <img src="img/logo.png" alt="logo">
        <nav>
            <ul>
                <li><a href="index.php" title="Accueil">Accueil</a></li>
                <li id="current"><a href="easymap.php" title="carte des lieux">Map</a></li>
                <li><a href="menus.html">Menus</a></li>
                <li><a href="contacts.html">Contact</a></li>
            </ul>
        </nav>
    </header>

    <main class="maineasymap">

        <section class="filtres">
            <form action="#" method="post">
            <input type="text" name="name" >
            <input type="text" name="type" >
            <button type="submit">OK</button>
            </form>
        </section>

        <div class="mapListContainer">
            <div id="mapid"></div>

            <div class="listpoi">

                <?php foreach ($poi as $item): ?>
                    <div id="item<?= $item['idi'] ?>" class="item js-marker" data-type="<?= $item['type'] ?>" data-name="<?= $item['name'] ?>" data-lat="<?= $item['lat'] ?>" data-long="<?= $item['longitude'] ?>"><a href="details.php?id=<?=$item['idi'] ?>">
                <img src="https://fakeimg.pl/200/">
                <h2><?= $item['name'] ?></h2>
                <p><?= $item['type'] ?></p>
                Détails</a>
            </div>
                <?php endforeach;?>
            </div>  
    </main>

    <footer class="footer">
        <div class="container cols cols--2 gutter">

            <section class="social">
                <h2>Sur les réseaux sociaux</h2>
                <div>
                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </section>
            <nav>
                <h2>A propos</h2>
                <ul class="unstyled">
                    <li><a href="#">Qui sommes-nous ?</a></li>
                    <li><a href="#">Nos services</a></li>
                    <li><a href="#">Contactez-nous</a></li>
                </ul>
            </nav>
            <nav>
                <h2>A propos</h2>
                <ul class="unstyled">
                    <li><a href="#">Plan du site</a></li>
                    <li><a href="#">Foire Aux Questions</a></li>

                    <li><a href="#">Informations légales</a></li>
                </ul>
            </nav>
        </div>
    </footer>
    <!-- Chargement librairie JS Leaflet pour affichage de la carte -->
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
   integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
   crossorigin=""></script>
    <script src="js/main.js"></script>
</body>

</html>