<!DOCTYPE html>
<html lang="fr">

<?php
require ('Views/inc/head.phtml');
?>

<body>

<?php
require ('Views/inc/header.phtml');
?>

    <main class="maineasymap">

        <section class="filtres">
            <form action="#" method="post">
            <input type="text" name="name" >
            <input type="text" name="type" >
            <button type="submit">OK</button>
            </form>
            <?php 
            if ($count>0){
                echo "<p>Il y a " .$count. " résultat(s) à votre recherche</p>";
            }else{
                echo "<p>Il n'y a aucun résultat à votre recherche!</p>";
            }
            ?>
        </section>

        <div class="mapListContainer">
            <div id="mapid"></div>

            <div class="listpoi">

                <?php foreach ($poi as $item): ?>
                    <div id="item<?= $item['idi'] ?>" class="item js-marker" data-type="<?= $item['type'] ?>" data-name="<?= $item['name'] ?>" data-lat="<?= $item['lat'] ?>" data-long="<?= $item['longitude'] ?>"><a href="details.php?id=<?=$item['idi'] ?>" title="page de détails">
                <img src="https://fakeimg.pl/200/" alt="photo poi">
                <h2><?= $item['name'] ?></h2>
                <p><?= $item['type'] ?></p>
                </a>
            </div>
                <?php endforeach;?>
            </div>  
    </main>

<?php
require ('inc/footer.phtml');
?>

    <!-- Chargement librairie JS Leaflet pour affichage de la carte -->
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"
   integrity="sha512-XQoYMqMTK8LvdxXYG3nZ448hOEQiglfqkJs1NOQV44cWnUrBc8PkAOcXy20w0vlaXaVUearIOBhiXZ5V3ynxwA=="
   crossorigin=""></script>

   <!-- Chargement JS -->
    <script src="js/main.js"></script>
</body>

</html>