
<main class="editProfilContainer">


    <!-- notifications   -->
    <?php
    require 'inc/notifications.phtml';
    ?>

    <h1>Edition de vos informations</h1>
    <section class="editProfil">

        <!-- Navigation dans le profil -->
        <nav class="sidenav">
        <a href="profil">Retour au profil</a>
        <a href="editprofil">Éditer mes informations</a>
        <a href="editpwd">Modifier mon mot de passe</a>

        <!-- Affichage du raccourci admin si admin -->
        <?php if (isset($_SESSION['user']['role'])) :
            if ($_SESSION['user']['role'] == 1) : ?>
            <a href="admin/administration">Administration</a>
            <?php endif; ?>
        <?php endif; ?>
        <a href="deconnexion">Déconnexion</a>
        </nav>

        <div class="display">  
            
            <!-- Formulaire de modification -->
            <fieldset >
                <legend>Merci de remplir les informations à modifier.</legend>
                <form role="form" action="editprofil" method="POST" class="formulaire">
                    <div class="form-group">
                        <label for="mail"><i class="fas fa-envelope"></i></label>
                        <input type="email" name="mail" class="form-control input-sm" value="<?= htmlspecialchars($_SESSION["user"]["mail"]) ?>" required>
                    </div>
                    <div class="form-group">
                        <label for="ville"><i class="fas fa-house-user"></i></label>
                        <input type="text" name="ville" class="ville" value="<?= htmlspecialchars($_SESSION["user"]["ville"]) ?>" required>
                    </div>
                    <div class="input-group-append">
                        <button type="submit" class="btnForm">Validez</button>
                    </div>
                </form>
            </fieldset>
        </div>
        
    </section>
</main>
