<?php
require('inc/head.phtml');

require('inc/header.phtml');
?>
<main class="editProfilContainer">


    <!-- notifications   -->
    <?php
    require 'inc/notifications.phtml';
    ?>

    <!--Formulaire de connexion-->
    <h1>Edition de vos informations</h1>
    <div class="formulaire">
        <fieldset>
            <legend>Merci de remplir les informations à modifier.</legend>
            <form role="form" action="editprofil.php" method="POST" class="formulaire">
                <div class="form-group">
                    <label for="mail"><i class="fas fa-envelope"></i></label>
                    <input type="email" name="mail" class="form-control input-sm" value="<?= $_SESSION["user"]["mail"] ?>" required>
                </div>
                <div class="form-group">
                    <label for="ville"><i class="fas fa-house-user"></i></label>
                    <input type="text" name="ville" class="ville" value="<?= $_SESSION["user"]["ville"] ?>" required>
                </div>
                <div class="input-group-append">
                    <button type="submit" class="btnForm">Validez</button>
                </div>
            </form>
        </fieldset>
    </div>
</main>

<?php require('views/inc/footer.phtml');
?>
</body>

</html>