<main class="editPwdContainer">
    <!-- notifications   -->
    <?php
    require 'inc/notifications.phtml';
    ?>
    <!--Formulaire de connexion-->
    <h1>Edition de votre mot de passe</h1>
    <section class="editpwd">
        <nav class="sidenav">
            <a href="profil">Retour au profil</a>
            <a href="editprofil">Éditer mes informations</a>
            <a href="editpwd">Modifier mon mot de passe</a>
            <?php if (isset($_SESSION['user']['role'])) :
                if ($_SESSION['user']['role'] == 1) : ?>
                <a href="admin/administration">Administration</a>
            <?php endif; ?>
            <?php endif; ?>
            <a href="deconnexion">Déconnexion</a>
        </nav>
        <div>
        <fieldset class="formulaire">
            <legend>Merci de remplir les informations à modifier.</legend>
            <form role="form" action="editpwd" method="POST" class="formulaire">
                <div class="form-group">
                    <p>Par sécurité, entrez votre mot de passe actuel en premier</p>
                    <label for="password3"><i class="fab fa-keycdn"></i></label>
                    <input type="password" name="password3" class="password" placeholder="Actuel" required>
                </div>
                <div class="form-group">
                    <label for="password"><i class="fas fa-key"></i></label>
                    <input type="password" name="password" class="password" placeholder="Nouveau Mot de Passe" required>
                </div>
                <div class="form-group">
                    <label for="password2"><i class="fas fa-lock"></i></label>
                    <input type="password" name="password2" class="password" placeholder="Le ressaisir" required>
                </div>
                <div class="input-group-append">
                    <button type="submit" class="btnForm">Modifier</button>
                </div>
            </form>
        </fieldset>
        </div>
    </section>
</main>