<?php
require('inc/head.phtml');

require('inc/header.phtml');
?>
<main class="editPwdContainer">

    <!-- notifications   -->
    <?php
    require 'inc/notifications.phtml';
    ?>


    <!--Formulaire de connexion-->
    <h1>Edition de votre mot de passe</h1>
    <div class="formulaire">
        <fieldset>
            <legend>Merci de remplir les informations à modifier.</legend>
            <form role="form" action="editpwd.php" method="POST" class="formulaire">
                <div class="form-group">
                    <p>Par sécurité, entrez votre mot de passe actuel</p>
                    <label for="password3"><i class="fab fa-keycdn"></i></label>
                    <input type="password" name="password3" class="password" placeholder="Votre Mot de Passe actuel" required>
                </div>
                <div class="form-group">
                <label for="password"><i class="fas fa-key"></i></label>
                    <input type="password" name="password" class="password" placeholder="Votre nouveau Mot de Passe" required>
                </div>
                <div class="form-group">
                <label for="password2"><i class="fas fa-lock"></i></label>
                    <input type="password" name="password2" class="password" placeholder="Vérification du mot de passe" required>
                </div>
                <div class="input-group-append">
                    <button type="submit" class="btnForm">Modifier</button>
                </div>
            </form>
        </fieldset>
    </div>
</main>

<?php require('views/inc/footer.phtml');
?>
</body>
</html>