<?php 
require ('inc/head.phtml');
require ('inc/header.phtml');
?>

<main class="mainInscription">   
    <form role="form" action="inscription.php" method="POST">
        <div class="form-group">
            <input type="text" name="pseudo" id="pseudo" class="form-control input-sm" placeholder="Votre Pseudo" required>
        </div>
		<div class="form-group">
			<input type="email" name="mail" id="mail" class="form-control input-sm" placeholder="Votre Email" required>
		</div>
		<div class="form-group">
            <div class="form-group">
                <input type="text" name="ville" id="ville" class="ville" placeholder="Ville de résidence" required>
            </div>
			<input type="password" name="password" id="password" class="password" placeholder="Votre Mot de Passe" required>
		</div>
		<div class="form-group">
			<input type="password" name="password2" id="verif-password" class="password" placeholder="Resaisir" required>
		</div>
		<div class="input-group-append">
            <button type="submit" id="envoyer" class="btn">Inscrivez Vous</button>
        </div>
	</form>
</main> 

<?php 
require ('inc/footer.phtml');
?>
    
</body>
</html>