<?php
require ('inc/head.phtml');
require ('inc/header.phtml');
?>
<main class="container">
  

  <!-- notifications   --> 
  <?php
  require 'inc/notifications.phtml';
  ?>
  
		  <!--Formulaire d'inscription'-->
	<h1>Page de profil</h1>
      <div class="profil">
        <span>Bienvenue <?= htmlspecialchars($_SESSION["user"]["pseudo"]) ?></span> <br />
        <span>Votre mail est : <?= htmlspecialchars($_SESSION["user"]["mail"]) ?></span> <br/>
        <div class="input-group-append">
             <a id="edit" href="editprofil.php" class="btn btn-primary">Editer Mon Profil</a>
             <a href="deconnexion.php"><button  type="submit" class="btnForm">Déconnexion</button></a>
        </div>         
    </div>      
   </main>
 <?php 
require ('inc/footer.phtml');
?>
    
</body>
</html>