
<main class="profilContainer">

<!-- notifications   -->
  <?php
  require 'inc/notifications.phtml';
  ?>

  <!--Formulaire d'inscription'-->
  <h1>Page de profil</h1>
  <div class="profil">
    <span>Bienvenue <?= htmlspecialchars($_SESSION["user"]["pseudo"]) ?></span> <br />
    <span>Votre mail est : <?= htmlspecialchars($_SESSION["user"]["mail"]) ?></span> <br />
    <span>Vous habitez : <?= htmlspecialchars($_SESSION["user"]["ville"]) ?></span> <br />
    <?php if (isset($_SESSION['user']['role'])) :
          if ($_SESSION['user']['role'] == 1) : ?>
        <span>La chance!! Vous êtes ADMINISTRATEUR OUAISSSSS</span>
        <a id="adm" href="admin/administration"><button class="btnForm">Administration</button></a>
    <?php endif; ?>
    <?php endif; ?>

    <div class="input-group-append">
      <a href="editprofil"><button class="btnForm">Éditer mes informations</button></a>
      <a href="editpwd"><button class="btnForm">Modifier mon mot de passe</button></a>
      <a href="deconnexion"><button class="btnForm">Déconnexion</button></a>
    </div>
  </div>
</main>