<main class="mainTags">

    <?php if (isset($_SESSION['user']['role']) && $_SESSION['user']['role'] === 1) : ?>
        <a href="admin/editpoi?id=<?= intval($_GET['id']) ?>" class="btnForm">Modifier</a>
    <?php endif ?>
    <h1>Détails sur l'accessibilité du lieu "<?= htmlspecialchars($details['name']); ?>"</h1>
    <a class="btnForm" href="details?id=<?=intval($_GET['id'])?>">Retour au lieu</a>
    <section class="accessibilite">
        <h2>L'accessibilité</h2>
            <form action="updatetags?id=<?= intval($_GET['id']) ?>" method="post">   
                <fieldset>
                <legend>Vous devez sélectionner à chaque fois la proposition qui correspond au lieu.</legend>
                    <p>Merci de compléter uniquement les informations que vous avez observé.</p>
                <div>
                    <h3>Le stationnement</h3>
                    <p>A 100m maximum, combien y'a t'il de stationnement(s) PMR?</p>
                        <select name="park" id="">
                           
                            <?php foreach($tagsPark as $park):?>
                                <option <?php if ($park['id'] === $details['tagsParkId']):?>
                         <?=  " selected "?>
                             <?php endif;?> 
                                
                                value="<?=intval($park['id'])?>"><?=htmlspecialchars($park['parking'])?></option>
                            <?php endforeach?>
                        </select>
                </div>
                <div>
                    <h3>L'accès au lieu</h3>
                    <p>Comment est l'entrée principal du lieu?</p>
                        <select name="entree" id="">
                           
                            <?php foreach($tagsEntree as $entree):?>
                                <option <?php if ($entree['id'] === $details['tagsEntreeId']):?>
                         <?=  " selected "?>
                             <?php endif;?>
                                
                                value="<?=intval($entree['id'])?>"><?=htmlspecialchars($entree['entree'])?></option>
                            <?php endforeach?>
                        </select>

                    <p>Comment est la porte du lieu?</p>
                        <select name="porte" id="">
                            
                            <?php foreach($tagsPorte as $porte):?>
                                <option <?php if ($porte['id'] === $details['tagsPorteId']):?>
                         <?=  " selected "?>
                             <?php endif;?>
                                value="<?=intval($porte['id'])?>"><?=htmlspecialchars($porte['porte'])?></option>
                            <?php endforeach?>
                        </select>       
                </div>
                <div>
                    <h3>L'intérieur du lieu</h3>
                    <p>Comment est la circulation dans le lieu?</p>
                        <select name="interieur" id="">
                            
                            <?php foreach($tagsInt as $int):?>
                                <option <?php if ($int['id'] === $details['tagsIntId']):?>
                         <?=  " selected "?>
                             <?php endif;?>
                                value="<?=intval($int['id'])?>"><?=htmlspecialchars($int['interieur'])?></option>
                            <?php endforeach?>
                        </select>
                    <p>Si il y a un comptoir comment est il?</p>
                        <select name="service" id="">
                            
                            <?php foreach($tagsService as $service):?>
                                <option <?php if ($service['id'] === $details['tagsServiceId']):?>
                         <?=  " selected "?>
                             <?php endif;?>
                                value="<?=intval($service['id'])?>"><?=htmlspecialchars($service['services'])?></option>
                            <?php endforeach?>
                        </select>
                    <p>Comment sont les toilettes?</p>
                        <select name="toilettes" id="">
                            
                            <?php foreach($tagsToilettes as $toilettes):?>
                                <option <?php if ($toilettes['id'] === $details['tagsToilettesId']):?>
                         <?=  " selected "?>
                             <?php endif;?>
                                value="<?=intval($toilettes['id'])?>"><?=htmlspecialchars($toilettes['toilettes'])?></option>
                            <?php endforeach?>
                        </select>
                </div>
                <div>
                    <h3>Le batiment</h3>
                    <p>Si c'est un bâtiment, a t'il des étages et peut on y accéder?</p>
                        <select name="batiment" id="">
                            
                            <?php foreach($tagsBat as $batiment):?>
                                <option <?php if ($batiment['id'] === $details['tagsBatimentId']):?>
                         <?=  " selected "?>
                             <?php endif;?>
                                value="<?=intval($batiment['id'])?>"><?=htmlspecialchars($batiment['batiment'])?></option>
                                <?php endforeach?>
                            </select>
                        </div>
    </section>
    <section class="avis">
        <h2>Votre avis : </h2>
        <p>Sur une échelle de 1 à 5, comment jugez vous l'accessibilité?</p>                                
        <p>1 étant impossible et 5 totale</p>                                
        <div class="star-rating__stars">               
            <input class="star-rating__input" type="radio" name="rating" value="1" id="rating-1" required/>
            <label class="star-rating__label" for="rating-1" aria-label="1/5"></label>
            <input class="star-rating__input" type="radio" name="rating" value="2" id="rating-2" />
            <label class="star-rating__label" for="rating-2" aria-label="2/5"></label>
            <input class="star-rating__input" type="radio" name="rating" value="3" id="rating-3" />
            <label class="star-rating__label" for="rating-3" aria-label="3/5e"></label>
            <input class="star-rating__input" type="radio" name="rating" value="4" id="rating-4" />
            <label class="star-rating__label" for="rating-4" aria-label="4/5"></label>
            <input class="star-rating__input" type="radio" name="rating" value="5" id="rating-5" />
            <label class="star-rating__label" for="rating-5" aria-label="5/5"></label>
            <div class="star-rating__focus"></div>
        </div>
        <button class="btnForm" type="submit">Soumettre</button>
                </fieldset>               
            </form> 
    </section>
</main>